# Generated by Django 6.0.7 on 2026-07-13 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(help_text='Short reading preview')),
                ('content', models.TextField(help_text='Markdown blog post content')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(help_text='Comma separated tags e.g. Deep Learning,RAG', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Role details, bullet points separated by newlines')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(help_text='Short card description')),
                ('long_description', models.TextField(blank=True, help_text='Detailed project description (Markdown supported)')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('tech_stack', models.CharField(help_text='Comma separated tags e.g. Django,React,PyTorch', max_length=300)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('backend', 'Backend & Systems'), ('frontend', 'Frontend'), ('ai_ml', 'AI/ML & Data Science'), ('advanced_ai', 'Advanced AI (Agents, RAGs, Workflows)'), ('tools', 'Tools & DevOps')], default='backend', max_length=50)),
                ('proficiency', models.CharField(blank=True, help_text='e.g. Expert, Advanced', max_length=50, null=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name or keyword', max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. AI/ML Engineer | Data Scientist', max_length=200)),
                ('bio', models.TextField(help_text='Short introductory bio')),
                ('about_me', models.TextField(help_text='Detailed markdown about me section')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
