# Generated by Django 6.0.7 on 2026-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color_theme',
            field=models.CharField(blank=True, help_text='Hex color theme e.g. #3776AB or #F62440', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Custom logo image URL or vector graphic', max_length=500, null=True),
        ),
    ]
