# Generated by Django 6.0.7 on 2026-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_skill_color_theme_skill_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percentage',
            field=models.IntegerField(default=85, help_text='Skill proficiency percentage from 0 to 100'),
        ),
    ]
