# Generated by Django 6.0.7 on 2026-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skill_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(help_text='e.g. neofetch, whoami, skills, help', max_length=100, unique=True)),
                ('response', models.TextField(help_text='Response output text returned when command is executed in terminal')),
                ('description', models.CharField(blank=True, help_text='Short description of what command does', max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'command'],
            },
        ),
    ]
