# Generated by Django 6.0.7 on 2026-08-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Short hover tooltip description of the skill, shown on hover', null=True),
        ),
    ]
