# Generated by Django 6.0.7 on 2026-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='Custom site favicon / tab title image URL (PNG, SVG, ICO)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seo_description',
            field=models.TextField(blank=True, help_text='SEO meta description for search engines and social cards', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_title',
            field=models.CharField(blank=True, help_text='Custom browser tab title and SEO title', max_length=200, null=True),
        ),
    ]
