# Generated by Django 6.0.7 on 2026-08-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_favicon_url_userprofile_seo_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('leetcode', 'LeetCode'), ('kaggle', 'Kaggle'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('mail', 'Email'), ('instagram', 'Instagram'), ('globe', 'Website / Globe'), ('link', 'Generic Link')], default='github', max_length=50)),
                ('label', models.CharField(help_text='Display title e.g. GitHub / LinkedIn', max_length=100)),
                ('url', models.CharField(help_text='Full destination URL or mailto link', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier (github, linkedin, twitter, etc.)', max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='footer_brand',
            field=models.CharField(blank=True, default='devil37', help_text='Brand name in the footer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='footer_text',
            field=models.CharField(blank=True, default='Built with Precision & Performance.', help_text='Custom copyright/tagline text shown in the footer', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kaggle_url',
            field=models.CharField(blank=True, help_text='Kaggle profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_url',
            field=models.CharField(blank=True, help_text='LeetCode profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.CharField(blank=True, help_text='Twitter / X profile URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.CharField(blank=True, help_text='YouTube channel URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
